### ISSUE TITLE
Starting stk-vis

### ISSUE THREAD

**Issue by vincenzoromeo** [lukasturcani/stk-vis#16]
How do you start stk-vis??

I couldn't find this in the Github page

**Comment by lukasturcani** [comment]
Hi there! If you download the `tar.gz` file for your platform, then extract it, the unzipped folder should have an `stk-vis` executable. On a Mac you can open it through the finder. You will have to right click, then press `Open` and then you will have a popup on which you have to click `open` again. Double clicking won't work on a Mac because tehre is some developer verification thing I haven't had time to look into.

Lemme know if this helps or not.
