### ISSUE TITLE
Be able to hide properties columns.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk-vis#23]
Self explanatory. Maybe a tock button next to the title to remove/hide a column? Or a drop down list, so you can easily re-show it?

**Comment by lukasturcani** [comment]
Atm, the best way to achieve this, is to move the columns around. So just move the ones you want to the left (drag and drop). But I'm gonna keep this open because I think it would be a nice to have.

**Comment by andrewtarzia** [comment]
Yes, I think this is a huge improvement on the current system when a database starts having > 5 properties.

**Comment by lukasturcani** [comment]
Ah yeah i can see how thats a pain

**Comment by lukasturcani** [comment]
OK, so my proposed user-facing solution is:

* A new button will need to be added. Kind of like the sorting button, it will open a new dialog.
* The dialog will contain a list of check boxes, one for each value collection.
* The check box will determine if the corresponding value collection has a column.
* The selection of shown / ignored collections will persist even if the user goes back to the Mongo configuration screen (the front page). I think this satisfies the principle of least annoyance because the use would have to re-toggle the check boxes otherwise. However, I can imagine a situation in which the user is going to be missing some columns they were expecting because they forgot the checkbox was off. This is a risk I'm willing to take.

The implementation:

* A new React component will need to be made, kind of like the sorting button.
* A new action will be made, when the checkbox is toggled, it dispatches this action. 
* There will be `ShowColumn String` and `HideColumn String` actions probably.
* The actions need to be implemented for the `UnsortedAll`, `UnsortedBuildingBlocks`, `UnsortedConstructedMolecules`, `SortedAll`, `SortedBuildingBlocks`, `SortedConstructedMolecules`, `BuildingBlockBrowser`, `StkVis` pages.
* The action will update the state by either adding or removing the collection from the ignored collections list in each of the pages states.
* I will need to figure out why this is an array currently, rather than a set. I will probably need to change it to a set.

Time estimates:
* I'm gonna estimate the adding of the React component at 6 hours because it has been a while since I touched that code. Plus I imagine getting the visuals right might take some effort. Estimate: 6 hours
* The adding of the action will probably be 30 minutes for the first page and then 5 minutes for the others because I think they are basically the same, so estimate is about an hour. Estimate: 1 hour
* Add another hour to make sure that the state associated with ignored collections is being passed around correctly. Estimate: 1 hour 
* And another 2 hours for figuring out why an array is being used instead of a set and convert to a set. Estimate: 2 hours
* Total Estimate:  10 hours

**Comment by andrewtarzia** [comment]
Love the plan - happy with the solution!
